# String for punctuation remove

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string

# As it was a txt file so we must mention how values are seperated inside file
# names=(Before and after(;) headings of entries)

In [86]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [87]:
df.head(5)

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [88]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [89]:
unqEmo=df['emotion'].unique()

# Dictionary creation for all unique values in output(One-Hot  encoding)

In [90]:
Emotions_numbers={}
i=0
for emo in unqEmo:
  Emotions_numbers[emo]=i
  i+=1

# Mapping means creating relation with dictionary and dataset

In [91]:
 df['emotion']=df['emotion'].map(Emotions_numbers)

In [92]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

# Converting text to lowercase
# Lambda: to create a small function

In [93]:
df['text']=df['text'].apply(lambda x:x.lower())

# Removing Punctuation

In [94]:
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [95]:
df['text']=df['text'].apply(remove_punc)

# Removing Numbers

In [96]:
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new=new+i
  return new

In [97]:
df['text']=df['text'].apply(remove_numbers)

# URLS AND LINKS REMOVING(This dataset is already cleaned because it's in kaggle) Just wrote this as a practice

In [98]:
import re

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

In [99]:
df['text'] = df['text'].apply(remove_urls)

# Removing emojis and HTML Tags
# Emojis have UNICODE not ASCII value

In [100]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
         new+=i
  return new

In [101]:
df['text']=df['text'].apply(remove_emojis)

# Stopwords Removing:Repeating words like(is,was,the) which generally give much meaning to sentence

# NLTK: Library good for stopwords
# corpus: For big collection of text
# Token:collection of it makes text(Individual symbol)
# Tokenization: process of converting text to tokens(individual values)

In [102]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# punkt: does tokenization

In [103]:
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

# All stopwords

In [104]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [105]:
len(stop_words)

198

# First go to every text step by step and extract text only
# Form an array of text in sentence seperatin each text with ""
# Then find stopword if there
# remove it

In [106]:
def remove(txt):
  words=word_tokenize(txt)
  cleaned=[]
  for i in words:
    if i not in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [107]:
df['text']=df['text'].apply(remove)

# Important

In [108]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

# Model Creation
# Data Split
# Don't confuse where is X and Y because always Input=x,Output=y

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

# Vectorization
# Input or text part(X_Train,X_Test)
# Output or Emotion Part   (Y_Train,Y_Test)
# countvectorizer=BagOW

In [121]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
vect=CountVectorizer()

# Using Bag Of Words model creation
# Naives Bayes

# Always fit (X_Train,Test) in Train Test split

In [123]:
Xtrain_vect=vect.fit_transform(X_train)
Xtest_vect=vect.transform(X_test)

In [112]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [125]:
model.fit(Xtrain_vect,y_train)

MultinomialNB()

In [127]:
y_pred=model.predict(Xtest_vect)

In [128]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7678125

In [129]:
y_pred

array([0, 5, 0, ..., 5, 5, 0])

# TFIDF Model creation

In [130]:
tfidf_vect=TfidfVectorizer()

In [136]:
Xtest_vect1=tfidf_vect.fit_transform(X_test)
Xtrain_vect2=tfidf_vect.transform(X_train)

In [138]:
model2=MultinomialNB()

In [139]:
model2.fit(Xtrain_vect2,y_train)

MultinomialNB()

In [140]:
y_pred1=model2.predict(Xtest_vect1)

In [141]:
acc=accuracy_score(y_test,y_pred1)

In [142]:
acc

0.7090625

# Logistics Regression

In [148]:
from sklearn.linear_model import LogisticRegression
model3=LogisticRegression(max_iter=1000)

In [149]:
model3.fit(Xtrain_vect2,y_train)

LogisticRegression(max_iter=1000)

In [152]:
y_logipred=model3.predict(Xtest_vect1)

In [153]:
acc1=accuracy_score(y_test,y_logipred)
acc1

0.8534375